export const cities = [
    { id: 1, name: "Lima" },
    { id: 2, name: "Cusco" },
    { id: 3, name: "Arequipa" },
    { id: 4, name: "Trujillo" },
    { id: 5, name: "Iquitos" },
    { id: 6, name: "Puno" },
    { id: 7, name: "Tacna" },
    { id: 8, name: "Piura" },
    { id: 9, name: "Tumbes" },
    { id: 10, name: "Moquegua" },
    { id: 11, name: "Madre de Dios" },
    { id: 12, name: "Apurimac" },
    { id: 13, name: "Ayacucho" },
    { id: 14, name: "Cajamarca" },
    { id: 15, name: "Callao" },
    { id: 16, name: "Huancavelica" },
    { id: 17, name: "Huanuco" },
    { id: 18, name: "Ica" },
    { id: 19, name: "Junin" },
    { id: 20, name: "La Libertad" },
    { id: 21, name: "Lambayeque" },
    { id: 22, name: "Loreto" },
    { id: 23, name: "Pasco" },
    { id: 24, name: "San Martín" },
    { id: 25, name: "Ucayali" }
  ];

  export const districtsByCity = {
    Lima: ["Miraflores", "San Isidro", "Barranco", "Surco", "La Molina", "San Borja", "Pueblo Libre"],
    Cusco: ["Cusco", "Machu Picchu", "Ollantaytambo", "Pisac", "Sacsayhuamán"],
    Arequipa: ["Arequipa", "Cayma", "Yanahuara", "Miraflores", "Paucarpata"],
    Trujillo: ["Trujillo", "El Porvenir", "Florencia de Mora", "La Esperanza", "Víctor Larco"],
    Iquitos: ["Iquitos", "Punchana", "Belén", "San Juan Bautista"],
    Puno: ["Puno", "Juliaca", "Chucuito", "Yunguyo"],
    Tacna: ["Tacna", "Alto de la Alianza", "Ciudad Nueva", "Pocollay"],
    Piura: ["Piura", "Sullana", "Catacaos", "Paita", "Sechura"],
    Tumbes: ["Tumbes", "Zarumilla", "Aguas Verdes", "Corrales"],
    Moquegua: ["Moquegua", "Ilo", "Torata", "Samegua"],
    "Madre de Dios": ["Puerto Maldonado", "Tambopata", "Las Piedras", "Inambari"],
    Apurimac: ["Abancay", "Andahuaylas", "Chincheros", "Talavera"],
    Ayacucho: ["Ayacucho", "Huanta", "Vilcashuamán", "Cangallo"],
    Cajamarca: ["Cajamarca", "Jaén", "Celendín", "Cajabamba"],
    Callao: ["Callao", "La Punta", "La Perla", "Bellavista", "Carmen de La Legua"],
    Huancavelica: ["Huancavelica", "Acobamba", "Lircay", "Castrovirreyna"],
    Huanuco: ["Huánuco", "Tingo María", "Aucayacu", "Ambo"],
    Ica: ["Ica", "Pisco", "Chincha Alta", "Nazca"],
    Junin: ["Huancayo", "El Tambo", "Chilca", "Otros"],
    "La Libertad": ["Trujillo", "Chepén", "Ascope", "Pacasmayo"],
    Lambayeque: ["Chiclayo", "Lambayeque", "Ferreñafe", "José Leonardo Ortiz"],
    Loreto: ["Iquitos", "Nauta", "Requena", "Yurimaguas"],
    Pasco: ["Cerro de Pasco", "Oxapampa", "Yanahuanca", "Villa Rica"],
    "San Martin": ["Moyobamba", "Tarapoto", "Lamas", "Juanjuí"],
    Ucayali: ["Pucallpa", "Atalaya", "Aguaytía", "Curimana"]
};  
  